version: '3.8'

services:
  todo-app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./todo-app:/app
    stdin_open: true
    tty: true
